/****** Object:  Database SqlMonitor    Script Date: 01/21/2011 16:13:15 ******/
CREATE DATABASE SqlMonitor 
GO
ALTER DATABASE SqlMonitor SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC SqlMonitor.[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE SqlMonitor SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE SqlMonitor SET ANSI_NULLS OFF
GO
ALTER DATABASE SqlMonitor SET ANSI_PADDING OFF
GO
ALTER DATABASE SqlMonitor SET ANSI_WARNINGS OFF
GO
ALTER DATABASE SqlMonitor SET ARITHABORT OFF
GO
ALTER DATABASE SqlMonitor SET AUTO_CLOSE ON
GO
ALTER DATABASE SqlMonitor SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE SqlMonitor SET AUTO_SHRINK OFF
GO
ALTER DATABASE SqlMonitor SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE SqlMonitor SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE SqlMonitor SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE SqlMonitor SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE SqlMonitor SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE SqlMonitor SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE SqlMonitor SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE SqlMonitor SET  ENABLE_BROKER
GO
ALTER DATABASE SqlMonitor SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE SqlMonitor SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE SqlMonitor SET TRUSTWORTHY OFF
GO
ALTER DATABASE SqlMonitor SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE SqlMonitor SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE SqlMonitor SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE SqlMonitor SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE SqlMonitor SET  READ_WRITE
GO
ALTER DATABASE SqlMonitor SET RECOVERY SIMPLE
GO
ALTER DATABASE SqlMonitor SET  MULTI_USER
GO
ALTER DATABASE SqlMonitor SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE SqlMonitor SET DB_CHAINING OFF
GO

